version: '3'
services:
  my-mysql:
    restart: always
    build: ./mysql/
    image: my-mysql
    networks:
      - spring-boot-mysql-network
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: abc
      MYSQL_ROOT_HOST: '%'

    ports:
      - "3306:3306"


  online-chat:
    depends_on:
      - my-mysql
    restart: on-failure
    build: ./
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - spring-boot-mysql-network
    environment:
      WAIT_HOSTS: my-mysql:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abc

networks:
  spring-boot-mysql-network:
    driver: bridge